# Generated by Django 4.1.5 on 2023-01-11 02:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0014_alter_avatars_created_at_alter_files_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatars',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='files',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='user_avatars',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='date created'),
        ),
    ]
