# Generated by Django 4.1.5 on 2023-01-11 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0015_alter_avatars_created_at_alter_files_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatars',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avatars',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='files',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='user_avatars',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created'),
        ),
    ]
