# Generated by Django 4.1.5 on 2023-01-11 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0016_avatars_image_url_alter_avatars_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_avatars',
            name='avatar_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
