# Generated by Django 4.1.5 on 2023-01-11 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0017_alter_user_avatars_avatar_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_avatars',
            name='avatar_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user_avatars',
            name='user_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
