# Generated by Django 4.1.5 on 2023-01-11 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0018_alter_user_avatars_avatar_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='file_type',
            field=models.CharField(default="", max_length=255, null=True, blank=True),
        )
    ]
