# Generated by Django 4.1.5 on 2023-01-11 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0019_alter_user_files_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_id', models.IntegerField(null=True)),
                ('question' , models.TextField(null=True, blank=True)),
                ('answer' , models.TextField(null=True, blank=True)),
                ('created_at', models.DateTimeField("date created", auto_now_add=True, null=True))
            ],
        ),
    ]
