# Generated by Django 4.1.5 on 2023-01-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0020_prompts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prompt',
            new_name='Prompts',
        )
    ]
