# Generated by Django 4.1.5 on 2023-01-20 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0021_rename_prompt_prompts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prompts',
            new_name='PresetQuestions',
        )
    ]
