# Generated by Django 4.1.5 on 2023-01-20 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0022_rename_prompts_presetquestions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prompts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('avatar_id', models.IntegerField(null=True)),
                ('value', models.TextField(blank=True, null=True)),
            ],
        )
    ]
