# Generated by Django 4.1.5 on 2023-01-11 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0026_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='restaurant_products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_id', models.IntegerField(null=True)),
                ('product_id', models.IntegerField(null=True))
            ],
        )
    ]